# Generated by Django 4.2.2 on 2023-06-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_showers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
