# Generated by Django 4.2.2 on 2023-06-27 06:14

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_lesson_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('sampletests', models.JSONField(default=courses.models.sample)),
                ('tests', models.JSONField(default=courses.models.sample)),
                ('errors', models.ManyToManyField(related_name='problem_errors', to=settings.AUTH_USER_MODEL)),
                ('solvers', models.ManyToManyField(related_name='problem_solvers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='', null=True)),
                ('language', models.CharField(max_length=20)),
                ('time', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='problems',
            field=models.ManyToManyField(related_name='lesson_problems', to='courses.problem'),
        ),
    ]
