# Generated by Django 4.2.2 on 2023-06-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attempt_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
